default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: smiles_development

test:
  <<: *default
  database: smiles_test

production:
  <<: *default
  database: smiles_production
  username: smiles
  password: <%= ENV['SMILES_DATABASE_PASSWORD'] %>
